{
    'name': 'KPI and Targets',
    'version': '1.0.0',
    'category': 'Extra Tools',
    'author': 'YannickCuvelie',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'contacts',
        'product',
        'account',
        'sale',
    ],
    'data': [
        'models/hello_world.xml',
        'security/hello_world_security.xml',
        'views/hello_world_views.xml',
        'views/hello_world_menu.xml',
        'views/res_partner_views.xml',
        'views/product_views.xml',
        'views/account_move_views.xml',
        'views/sale_order_views.xml',
    ],
    'installable': True,
    'application': True,
}