{
    "name": "Accounting Community",
    "version": "18.0.1.0.0",
    "category": "Reporting",
    "summary": "Financial Reporting Standard Reports",
    "author": "Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/account-financial-reporting",
    "depends": ["account", "date_range"],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "wizard/balance_sheet_wizard_view.xml",
        "wizard/profit_loss_wizard_view.xml",
        "wizard/general_ledger_wizard_view.xml",
        "wizard/partner_ledger_wizard_view.xml",
        "wizard/aged_receivables_wizard_view.xml",
        "wizard/aged_payables_wizard_view.xml",
        "wizard/trial_balance_wizard_view.xml",
        "wizard/tax_report_wizard_view.xml",
        "wizard/tax_audit_wizard_view.xml",
        "wizard/journal_ledger_wizard_view.xml",
        "wizard/financial_dashboard_wizard_view.xml",
        "menuitems.xml",
        "reports.xml",
        "view/balance_sheet.xml",
        "view/profit_loss.xml",
        "view/general_ledger.xml",
        "view/partner_ledger.xml",
        "view/aged_receivables.xml",
        "view/aged_payables.xml",
        "view/trial_balance.xml",
        "view/tax_report.xml",
        "view/tax_audit.xml",
        "view/journal_ledger.xml",
        "view/financial_dashboard.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "accounting_community/static/src/js/*",
            "accounting_community/static/src/xml/**/*",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "AGPL-3",
}